# Generated by Django 4.2.1 on 2023-06-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
